name: Lexware Export

on:
  schedule:
    - cron: "0 6 * * *"  # täglich um 6 Uhr
  workflow_dispatch:

jobs:
  run-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run invoice export
        env:
          LEXWARE_API_TOKEN: ${{ secrets.LEXWARE_API_TOKEN }}
        run: python lexware-invoice-export.py
